In [1]:
import numpy as np
import numpy.linalg as la
import time
from copy import deepcopy
from f_optimize import *

In [7]:
# def calculateHessian(x, calculateGrad, diff = 1e-5):
#     
#     hessian = np.zeros((x.shape[0], x.shape[0]))
#     
#     it = np.nditer(x, flags = ["multi_index"], op_flags = ["readwrite"])
#     
#     while not it.finished:
#         ix = it.multi_index
#         
#         oldVal = x[ix]
#         x[ix] = oldVal + diff
#         pos = calculateGrad(x).copy()
#         x[ix] = oldVal - diff
#         neg = calculateGrad(x).copy()
#         x[ix] = oldVal
#         hessian[ix] = (pos - neg) / (2 * diff)
#         it.iternext()
#     
#     return hessian

In [8]:
def objectiveFunc(x):
    """

    :param x: shape (D)
    :return: objective value shape (1)
    """
    
    # v = #PUT YOUR FUNCTION HERE
    # return np.array([v])
    pass

In [9]:
def customFunc(x):
    return np.array([(x[0] ** 4) - 1])
    # return np.array([np.log(np.exp(x[0]) + np.exp(- x[0]))])
    # return np.array([- np.log(x[0]) + x[0]])

def customFuncGrad(x):
    return calculateGrad(x, customFunc)

In [10]:
def paraboloid(x):
    return ((10 * (x[0] ** 2)) + (x[1] ** 2)) / 2

def paraboloidGrad(x):
    return np.array([10 * x[0], x[1]])

In [11]:
def parabolicCylinder(x):
    v = x[1] ** 2
    return np.array([v])

def parabolicCylinderGrad(x):
    return np.array([0, 2 * x[1]])

In [12]:
def rosenbrock2d(x):
    v = 100 * (x[1] - x[0]**2)**2 + (1 - x[0])**2
    return np.array([v])

def g_rosenbrock2d(x):
    v = np.zeros_like(x)
    v[0] = 400 * x[0]**3 - 400 * x[0] * x[1] + 2 * x[0] - 2
    v[1] = 200 * (x[1] - x[0]**2)
    return v

def h_rosenbrock2d(x):
    h = np.zeros((x.shape[0], x.shape[0]))
    h[0][0] = (-400 * x[1]) + (1200 * (x[0] ** 2)) + 2
    h[0][1] = -400 * x[0]
    h[1][0] = deepcopy(h[0][1])
    h[1][1] = 200
    return h

In [13]:
testX = np.random.rand(2)
calculateGrad(testX, rosenbrock2d) - g_rosenbrock2d(testX)

/tmp/ipykernel_125986/2543695520.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  grad[ix] = (pos - neg) / (2 * diff)


array([ 8.62383587e-09, -4.77626827e-10])

In [14]:
testX = np.random.rand(2)
calculateGrad(testX, g_rosenbrock2d) - h_rosenbrock2d(testX)

array([[ 3.95707147e-08, -2.52384780e-10],
       [ 4.58157956e-10, -1.17668719e-09]])

In [37]:
f_optimize(rosenbrock2d,
           g_rosenbrock2d,
           np.array([15,
                     10]),
           60)

After: 53845 iterations - 1.39026141 seconds
Objective value: 0.00000000


/tmp/ipykernel_125986/3855411996.py:58: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('Objective value: %.8f' % (f(x)))


array([1.00000056, 1.00000113])